# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HelloDouyu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloDouyu
  pod 'UIColor_Hex_Swift', '~> 4.2.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'DeviceKit', '~> 1.3'
  pod 'SnapKit', '~> 4.0.0'
  pod 'SwiftHandyFrame'


  target 'HelloDouyuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HelloDouyuUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
